name: Deploy to GH pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest-large

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3

      - name: Setup Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610  # v3
        with:
          node-version: "14.x"
          cache: 'yarn'

      - name: Installing Dependencies
        run: yarn install

      - name: Building App
        run: yarn build
        env:
          REACT_APP_SEGMENT_WRITE_KEY: ${{ secrets.REACT_APP_SEGMENT_WRITE_KEY }}

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
